# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import ctypes
myappid = 'mycompany.myproduct.subproduct.version' # arbitrary string
ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 674)
        MainWindow.setWindowIcon(QtGui.QIcon("resources/trayIcon.png"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.0199005, y1:0.966, x2:1, y2:1, stop:0 rgba(234, 141, 141, 255), stop:1 rgba(168, 144, 254, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.voiceRecButton = QtWidgets.QPushButton(self.centralwidget)
        self.voiceRecButton.setGeometry(QtCore.QRect(40, 210, 191, 51))
        self.voiceRecButton.setStyleSheet("QPushButton#voiceRecButton{\n"
"border-radius:22px;\n"
"color: rgb(217, 252, 248);\n"
"font: 63 8pt \"JetBrains Mono SemiBold\";\n"
"background-color: rgb(120, 188, 230);\n"
"}\n"
"QPushButton#voiceRecButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(129, 204, 248);\n"
"}\n"
"QPushButton#voiceRecButton:pressed{\n"
"\n"
"background-color: rgb(50, 188, 241);\n"
"}")
        self.voiceRecButton.setObjectName("voiceRecButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 630, 131, 51))
        self.label.setStyleSheet("font: 81 18pt \"JetBrains Mono ExtraBold\";")
        self.label.setObjectName("label")
        self.icon1 = QtWidgets.QLabel(self.centralwidget)
        self.icon1.setGeometry(QtCore.QRect(10, 640, 31, 31))
        self.icon1.setText("")
        self.icon1.setPixmap(QtGui.QPixmap("resources/logo.png"))
        self.icon1.setScaledContents(True)
        self.icon1.setObjectName("icon1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 648, 51, 21))
        self.label_2.setStyleSheet("\n"
"font: 25 14pt \"JetBrains Mono Light\";")
        self.label_2.setObjectName("label_2")
        self.voiceRecBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.voiceRecBrowser.setGeometry(QtCore.QRect(10, 0, 256, 192))
        self.voiceRecBrowser.setStyleSheet("border-radius:22px;\n"
"border: 0;\n"
"background-color: rgba(223, 201, 255,20);")
        self.voiceRecBrowser.setObjectName("voiceRecBrowser")
        self.botTalkButton = QtWidgets.QPushButton(self.centralwidget)
        self.botTalkButton.setGeometry(QtCore.QRect(369, 210, 191, 51))
        self.botTalkButton.setStyleSheet("QPushButton#botTalkButton{\n"
"border-radius:22px;\n"
"color: rgb(217, 252, 248);\n"
"font: 63 8pt \"JetBrains Mono SemiBold\";\n"
"background-color: rgb(120, 188, 230);\n"
"}\n"
"QPushButton#botTalkButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(129, 204, 248);\n"
"}\n"
"QPushButton#botTalkButton:pressed{\n"
"\n"
"background-color: rgb(50, 188, 241);\n"
"}")
        self.botTalkButton.setObjectName("botTalkButton")
        self.botTalkBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.botTalkBrowser.setGeometry(QtCore.QRect(334, 0, 256, 192))
        self.botTalkBrowser.setStyleSheet("border-radius:22px;\n"
"border: 10;\n"
"background-color: rgba(223, 201, 255,20);")
        self.botTalkBrowser.setObjectName("botTalkBrowser")
        self.fileRecognizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.fileRecognizeButton.setGeometry(QtCore.QRect(149, 550, 301, 51))
        self.fileRecognizeButton.setStyleSheet("QPushButton#fileRecognizeButton{\n"
"border-radius:22px;\n"
"color: rgb(217, 252, 248);\n"
"font: 63 8pt \"JetBrains Mono SemiBold\";\n"
"background-color: rgb(120, 188, 230);\n"
"}\n"
"QPushButton#fileRecognizeButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(129, 204, 248);\n"
"}\n"
"QPushButton#fileRecognizeButton:pressed{\n"
"\n"
"background-color: rgb(50, 188, 241);\n"
"}")
        self.fileRecognizeButton.setObjectName("fileRecognizeButton")
        self.fileBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.fileBrowser.setGeometry(QtCore.QRect(172, 340, 256, 192))
        self.fileBrowser.setStyleSheet("border-radius:22px;\n"
"border: 10;\n"
"background-color: rgba(223, 201, 255,20);")
        self.fileBrowser.setObjectName("fileBrowser")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(174, 320, 251, 16))
        self.label_3.setStyleSheet("color: rgb(217, 252, 248);\n"
"font: 63 7pt \"JetBrains Mono SemiBold\";")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.voiceRecButton.setText(_translate("MainWindow", "Voice recognition"))
        self.label.setText(_translate("MainWindow", "VRec"))
        self.label_2.setText(_translate("MainWindow", "1.0"))
        self.voiceRecBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">hello</p></body></html>"))
        self.botTalkButton.setText(_translate("MainWindow", "Make it say something!"))
        self.botTalkBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">hello</p></body></html>"))
        self.fileRecognizeButton.setText(_translate("MainWindow", "Choose file to recognize voice from"))
        self.fileBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">hello</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Voice recognized from file is here:"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()

    MainWindow.setWindowTitle("VRec")
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
